// API Keys for map application
const GOOGLE_MAPS_API_KEY = 'YOUR_GOOGLE_MAPS_API_KEY';
const WEATHERSTACK_API_KEY = 'YOUR_WEATHERSTACK_API_KEY';
const TOMTOM_API_KEY = 'YOUR_TOMTOM_API_KEY';
const OPENCHARGEMAP_API_KEY = 'YOUR_OPENCHARGEMAP_API_KEY';
